### PR TITLE
replace unsafe reading of struct with safe code

### PR DESCRIPTION
**Pull request by icewind1991**
Also includes reformatting and moving things to rust2018

### CODE REVIEW

**Comment by roman901** [comment]
Oh, do you _really_ use my code? 😮 

I have played with `impl Read` for headers, thank you for working solution

**Comment by icewind1991** [comment]
> Oh, do you really use my code

have some ideas that would be using it, so might as well improve it a bit along the way :)

**Comment by roman901** [comment]
Quickly looked at your repositories - do you want to create an model renderer/editor? :)

**Comment by icewind1991** [comment]
pretty much, have some ideas that involve loading tf2 maps

**Pull request merged**
